### ISSUE TITLE
Generating Project files fails ?

### ISSUE THREAD

**Issue by sumisukyo** [oculus-samples/Unreal-SharedSpaces#108]
ERROR 
'EngineIncludeOrderVersion' does not contain a definition for 'Unreal5_5'

Steps:
Follow install guide
Double checked version 5.4
Follow Engine guide, works making sample vr project
Follow guide to open SharedSpaces project
Get this error when trying to Generate Project files.

Can't find other examples of this happening, I don't understand why it thinks this engine is 5.5 ?
The downloaded file name is UnrealEngine-oculus-5.4.zip

Help me Obi-won Kenobi

```
Generating VisualStudio project files:
Discovering modules, targets and source code for project...
Compiled assembly file 'G:\WIP Games\Unreal Engine 5\Unreal-SharedSpaces\Intermediate\Build\BuildRules\SharedSpacesModuleRules.dll' appears to be for a newer CLR version or is otherwise invalid.  Unreal Build Tool will try to recompile this assembly now.  (Exception: Could not load file or assembly 'G:\WIP Games\Unreal Engine 5\Unreal-SharedSpaces\Intermediate\Build\BuildRules\SharedSpacesModuleRules.dll'. Format of the executable (.exe) or library (.dll) is invalid.)
G:\WIP Games\Unreal Engine 5\Unreal-SharedSpaces\Source\SharedSpacesEditor.Target.cs(15,51): error CS0117: 'EngineIncludeOrderVersion' does not contain a definition for 'Unreal5_5'
G:\WIP Games\Unreal Engine 5\Unreal-SharedSpaces\Source\SharedSpaces.Target.cs(16,51): error CS0117: 'EngineIncludeOrderVersion' does not contain a definition for 'Unreal5_5'
Total execution time: 1.82 seconds
Expecting to find a type to be declared in a target rules named 'SharedSpacesTarget'.  This type must derive from the 'TargetRules' type defined by UnrealBuildTool.
```

**Comment by sumisukyo** [comment]
Ow is the shared spaces on 5.5 but the instructions are outdated for engine 5.4 ?

**Comment by sumisukyo** [comment]
SharedSpaces-main-5.x Generates but fails to open due to the plugin needing 5.5 so trying that engine next.

**Comment by mderzelle** [comment]
That is right,
On February the project has been updated to use UE5.5 and SDK v72.

An update to the README is on its way.

Tell me if it works for you with UE5.5 so that I'll close the issue.

**Comment by alefriant** [comment]
Hi @sumisukyo

I still use the old SharedSpaces with Photon and it works fine, but I’m very interested in using the new EOS version. However, with UE 5.5.0 and SDK v72 I can’t get EOS to connect (it doesn’t log in or join any rooms). The last time I tested was with UE 5.5 and SDK v72, and I see there’s now UE 5.5.3 and SDK v77, if you can get it working with that in a shipping build, that would be great to know. 

Has anyone managed to get it working in shipping with any 5.5.X setup?
